import json
import os
import time

# Path to the shared Mininet → Mac → MACDS bridge file
EVENT_FILE = os.path.expanduser("~/mininet_bridge/mininet_attack_event.json")

# Track last processed modification time
_last_processed_time = 0


def detect_attack():
    """
    Reads real attack events generated by Mininet.
    Returns:
        {
            "attack": "ddos",
            "source_ip": "10.0.0.3",
            "rate": 250.0
        }
    Or:
        None  (if no new attack event)
    """

    global _last_processed_time

    # File does not exist → no attack
    if not os.path.exists(EVENT_FILE):
        return None

    try:
        # Check if file is new / updated
        mtime = os.path.getmtime(EVENT_FILE)
        if mtime <= _last_processed_time:
            return None

        _last_processed_time = mtime

        # Load event
        with open(EVENT_FILE, "r") as f:
            event = json.load(f)

        # Validate required fields
        attack_type = event.get("attack")
        attacker_ip = event.get("attacker_ip")
        packet_rate = event.get("packet_rate")

        if not attack_type or not attacker_ip:
            return None

        return {
            "attack": attack_type,
            "source_ip": attacker_ip,
            "rate": packet_rate,
        }

    except Exception as e:
        # Any parsing / IO error → fail safely
        return None
